import {TYPE} from './models/ProductModel';


export const MOCK_DATA = {
    [TYPE.CUA]: [
        {
            'id': 698,
            'name': 'A.CS1 Cửa sổ thép sơn vân gỗ 1 cánh, không ô thoáng',
            'day_canh': '40',
            'quy_cach_canh': '1_canh',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_so',
        },
        {
            'id': 1922,
            'name': 'A.CS1-Fix Cửa sổ thép sơn vân gỗ 1 cánh, ô thoáng fix huỳnh',
            'day_canh': '40',
            'quy_cach_canh': '1_canh',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_so',
        },
        {
            'id': 699,
            'name': 'A.CS1-K Cửa sổ thép sơn vân gỗ 1 cánh, ô thoáng kính',
            'day_canh': '40',
            'quy_cach_canh': '1_canh',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_so',
        },
        {
            'id': 700,
            'name': 'A.CS1-NC Cửa sổ thép sơn vân gỗ 1 cánh, ô thoáng nan chớp',
            'day_canh': '40',
            'quy_cach_canh': '1_canh',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_so',
        },
        {
            'id': 1923,
            'name': 'A.CS1-SH Cửa sổ thép sơn vân gỗ 1 cánh, ô thoáng sen hoa',
            'day_canh': '40',
            'quy_cach_canh': '1_canh',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_so',
        },
        {
            'id': 701,
            'name': 'A.CS1-V Cửa sổ thép sơn vân gỗ 1 cánh, ô thoáng vòm',
            'day_canh': '40',
            'quy_cach_canh': '1_canh',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_so',
        },
        {
            'id': 702,
            'name': 'A.CS2 Cửa sổ thép sơn vân gỗ 2 cánh, không ô thoáng',
            'day_canh': '40',
            'quy_cach_canh': '2_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_so',
        },
        {
            'id': 1924,
            'name': 'A.CS2-Fix Cửa sổ thép sơn vân gỗ 2 cánh, ô thoáng fix huỳnh',
            'day_canh': '40',
            'quy_cach_canh': '2_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_so',
        },
        {
            'id': 703,
            'name': 'A.CS2-K Cửa sổ thép sơn vân gỗ 2 cánh, ô thoáng kính',
            'day_canh': '40',
            'quy_cach_canh': '2_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_so',
        },
        {
            'id': 704,
            'name': 'A.CS2-NC Cửa sổ thép sơn vân gỗ 2 cánh, ô thoáng nan chớp',
            'day_canh': '40',
            'quy_cach_canh': '2_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_so',
        },
        {
            'id': 1925,
            'name': 'A.CS2-SH Cửa sổ thép sơn vân gỗ 2 cánh, ô thoáng sen hoa',
            'day_canh': '40',
            'quy_cach_canh': '2_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_so',
        },
        {
            'id': 705,
            'name': 'A.CS2-V Cửa sổ thép sơn vân gỗ 2 cánh, ô thoáng vòm',
            'day_canh': '40',
            'quy_cach_canh': '2_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_so',
        },
        {
            'id': 706,
            'name': 'A.CS3 Cửa sổ thép sơn vân gỗ 3 cánh, không ô thoáng',
            'day_canh': '40',
            'quy_cach_canh': '3_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_so',
        },
        {
            'id': 1926,
            'name': 'A.CS3-Fix Cửa sổ thép sơn vân gỗ 3 cánh, ô thoáng fix huỳnh',
            'day_canh': '40',
            'quy_cach_canh': '3_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_so',
        },
        {
            'id': 707,
            'name': 'A.CS3-K Cửa sổ thép sơn vân gỗ 3 cánh, ô thoáng kính',
            'day_canh': '40',
            'quy_cach_canh': '3_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_so',
        },
        {
            'id': 708,
            'name': 'A.CS3-NC Cửa sổ thép sơn vân gỗ 3 cánh, ô thoáng nan chớp',
            'day_canh': '40',
            'quy_cach_canh': '3_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_so',
        },
        {
            'id': 1927,
            'name': 'A.CS3-SH Cửa sổ thép sơn vân gỗ 3 cánh, ô thoáng sen hoa',
            'day_canh': '40',
            'quy_cach_canh': '3_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_so',
        },
        {
            'id': 709,
            'name': 'A.CS3-V Cửa sổ thép sơn vân gỗ 3 cánh, ô thoáng vòm',
            'day_canh': '40',
            'quy_cach_canh': '3_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_so',
        },
        {
            'id': 710,
            'name': 'A.CS4 Cửa sổ thép sơn vân gỗ 4 cánh, không ô thoáng',
            'day_canh': '40',
            'quy_cach_canh': '4_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_so',
        },
        {
            'id': 1928,
            'name': 'A.CS4-Fix Cửa sổ thép sơn vân gỗ 4 cánh, ô thoáng fix huỳnh',
            'day_canh': '40',
            'quy_cach_canh': '4_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_so',
        },
        {
            'id': 711,
            'name': 'A.CS4-K Cửa sổ thép sơn vân gỗ 4 cánh, ô thoáng kính',
            'day_canh': '40',
            'quy_cach_canh': '4_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_so',
        },
        {
            'id': 712,
            'name': 'A.CS4-NC Cửa sổ thép sơn vân gỗ 4 cánh, ô thoáng nan chớp',
            'day_canh': '40',
            'quy_cach_canh': '4_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_so',
        },
        {
            'id': 1929,
            'name': 'A.CS4-SH Cửa sổ thép sơn vân gỗ 4 cánh, ô thoáng sen hoa',
            'day_canh': '40',
            'quy_cach_canh': '4_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_so',
        },
        {
            'id': 713,
            'name': 'A.CS4-V Cửa sổ thép sơn vân gỗ 4 cánh, ô thoáng vòm',
            'day_canh': '40',
            'quy_cach_canh': '4_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_so',
        },
        {
            'id': 3204,
            'name': 'A.CS5 Cửa sổ thép sơn vân gỗ 4 cánh lệch, không ô thoáng',
            'day_canh': '40',
            'quy_cach_canh': '4_canh_lech',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_so',
        },
        {
            'id': 3223,
            'name': 'A.CS5-Fix Cửa sổ thép sơn vân gỗ 4 cánh, ô thoáng fix huỳnh',
            'day_canh': '40',
            'quy_cach_canh': '4_canh_lech',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_so',
        },
        {
            'id': 3203,
            'name': 'A.CS5-K Cửa sổ thép sơn vân gỗ 4 cánh lệch, ô thoáng kính',
            'day_canh': '40',
            'quy_cach_canh': '4_canh_lech',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_so',
        },
        {
            'id': 3205,
            'name': 'A.CS5-NC Cửa sổ thép sơn vân gỗ 4 cánh lệch, ô thoáng nan chớp',
            'day_canh': '40',
            'quy_cach_canh': '4_canh_lech',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_so',
        },
        {
            'id': 3206,
            'name': 'A.CS5-SH Cửa sổ thép sơn vân gỗ 4 cánh lệch, ô thoáng sen hoa',
            'day_canh': '40',
            'quy_cach_canh': '4_canh_lech',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_so',
        },
        {
            'id': 3207,
            'name': 'A.CS5-V Cửa sổ thép sơn vân gỗ 4 cánh lệch, ô thoáng vòm',
            'day_canh': '40',
            'quy_cach_canh': '4_canh_lech',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_so',
        },
        {
            'id': 656,
            'name': 'A1 Cửa đi 1 cánh thép sơn vân gỗ, không ô thoáng',
            'day_canh': '50',
            'quy_cach_canh': '1_canh',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_chinh',
        },
        {
            'id': 657,
            'name': 'A1-Fix Cửa đi 1 cánh thép sơn vân gỗ, ô thoáng fix',
            'day_canh': '50',
            'quy_cach_canh': '1_canh',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_chinh',
        },
        {
            'id': 658,
            'name': 'A1-K Cửa đi 1 cánh thép sơn vân gỗ, ô thoáng kính',
            'day_canh': '50',
            'quy_cach_canh': '1_canh',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_chinh',
        },
        {
            'id': 659,
            'name': 'A1-NC Cửa đi 1 cánh thép sơn vân gỗ, ô thoáng nan chớp',
            'day_canh': '50',
            'quy_cach_canh': '1_canh',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_chinh',
        },
        {
            'id': 661,
            'name': 'A1-SH Cửa đi 1 cánh thép sơn vân gỗ, ô thoáng sen hoa',
            'day_canh': '50',
            'quy_cach_canh': '1_canh',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_chinh',
        },
        {
            'id': 655,
            'name': 'A1-TC Cửa đi 1 cánh thép sơn vân gỗ, không ô thoáng (sản xuất sẵn)',
            'day_canh': '50',
            'quy_cach_canh': '1_canh',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_chinh',
        },
        {
            'id': 660,
            'name': 'A1-V Cửa đi 1 cánh thép sơn vân gỗ, ô thoáng vòm',
            'day_canh': '50',
            'quy_cach_canh': '1_canh',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_chinh',
        },
        {
            'id': 670,
            'name': 'A21 Cửa đi 2 cánh lệch thép sơn vân gỗ, không ô thoáng',
            'day_canh': '50',
            'quy_cach_canh': '2_canh_lech',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_chinh',
        },
        {
            'id': 671,
            'name': 'A21-Fix Cửa đi 2 cánh lệch thép sơn vân gỗ, ô thoáng fix',
            'day_canh': '50',
            'quy_cach_canh': '2_canh_lech',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_chinh',
        },
        {
            'id': 672,
            'name': 'A21-K Cửa đi 2 cánh lệch thép sơn vân gỗ, ô thoáng kính',
            'day_canh': '50',
            'quy_cach_canh': '2_canh_lech',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_chinh',
        },
        {
            'id': 673,
            'name': 'A21-NC Cửa đi 2 cánh lệch thép sơn vân gỗ, ô thoáng nan chớp',
            'day_canh': '50',
            'quy_cach_canh': '2_canh_lech',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_chinh',
        },
        {
            'id': 677,
            'name': 'A21-SH Cửa đi 2 cánh lệch thép sơn vân gỗ, ô thoáng sen hoa',
            'day_canh': '50',
            'quy_cach_canh': '2_canh_lech',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_chinh',
        },
        {
            'id': 676,
            'name': 'A21-V Cửa đi 2 cánh lệch thép sơn vân gỗ, ô thoáng vòm',
            'day_canh': '50',
            'quy_cach_canh': '2_canh_lech',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_chinh',
        },
        {
            'id': 675,
            'name': 'A21-VFix Cửa đi 2 cánh lệch thép sơn vân gỗ, có vách fix',
            'day_canh': '50',
            'quy_cach_canh': '2_canh_lech',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_chinh',
        },
        {
            'id': 674,
            'name': 'A21-VK Cửa đi 2 cánh lệch thép sơn vân gỗ, có vách kính',
            'day_canh': '50',
            'quy_cach_canh': '2_canh_lech',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_chinh',
        },
        {
            'id': 662,
            'name': 'A22 Cửa đi 2 cánh cân thép sơn vân gỗ, không ô thoáng',
            'day_canh': '50',
            'quy_cach_canh': '2_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_chinh',
        },
        {
            'id': 663,
            'name': 'A22-Fix Cửa đi 2 cánh cân thép sơn vân gỗ, ô thoáng fix',
            'day_canh': '50',
            'quy_cach_canh': '2_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_chinh',
        },
        {
            'id': 664,
            'name': 'A22-K Cửa đi 2 cánh cân thép sơn vân gỗ, ô thoáng kính',
            'day_canh': '50',
            'quy_cach_canh': '2_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_chinh',
        },
        {
            'id': 665,
            'name': 'A22-NC Cửa đi 2 cánh cân thép sơn vân gỗ, ô thoáng nan chớp',
            'day_canh': '50',
            'quy_cach_canh': '2_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_chinh',
        },
        {
            'id': 669,
            'name': 'A22-SH Cửa đi 2 cánh thép sơn vân gỗ, ô thoáng sen hoa',
            'day_canh': '50',
            'quy_cach_canh': '2_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_chinh',
        },
        {
            'id': 668,
            'name': 'A22-V Cửa đi 2 cánh cân thép sơn vân gỗ, ô thoáng vòm',
            'day_canh': '50',
            'quy_cach_canh': '2_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_chinh',
        },
        {
            'id': 667,
            'name': 'A22-VFix Cửa đi 2 cánh cân thép sơn vân gỗ, có vách fix',
            'day_canh': '50',
            'quy_cach_canh': '2_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_chinh',
        },
        {
            'id': 666,
            'name': 'A22-VK Cửa đi 2 cánh cân thép sơn vân gỗ, có vách kính',
            'day_canh': '50',
            'quy_cach_canh': '2_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_chinh',
        },
        {
            'id': 682,
            'name': 'A42 Cửa đi 4 cánh lệch thép sơn vân gỗ, không ô thoáng',
            'day_canh': '50',
            'quy_cach_canh': '4_canh_lech',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_chinh',
        },
        {
            'id': 683,
            'name': 'A42-Fix Cửa đi 4 cánh lệch thép sơn vân gỗ, ô thoáng fix',
            'day_canh': '50',
            'quy_cach_canh': '4_canh_lech',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_chinh',
        },
        {
            'id': 684,
            'name': 'A42-K Cửa đi 4 cánh lệch thép sơn vân gỗ, ô thoáng kính',
            'day_canh': '50',
            'quy_cach_canh': '4_canh_lech',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_chinh',
        },
        {
            'id': 685,
            'name': 'A42-NC Cửa đi 4 cánh lệch thép sơn vân gỗ, ô thoáng nan chớp',
            'day_canh': '50',
            'quy_cach_canh': '4_canh_lech',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_chinh',
        },
        {
            'id': 689,
            'name': 'A42-SH Cửa đi 4 cánh lệch thép sơn vân gỗ, ô thoáng sen hoa',
            'day_canh': '50',
            'quy_cach_canh': '4_canh_lech',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_chinh',
        },
        {
            'id': 688,
            'name': 'A42-V Cửa đi 4 cánh lệch thép sơn vân gỗ, ô thoáng vòm',
            'day_canh': '50',
            'quy_cach_canh': '4_canh_lech',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_chinh',
        },
        {
            'id': 687,
            'name': 'A42-VFix Cửa đi 4 cánh lệch thép sơn vân gỗ, có vách fix',
            'day_canh': '50',
            'quy_cach_canh': '4_canh_lech',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_chinh',
        },
        {
            'id': 686,
            'name': 'A42-VK Cửa đi 4 cánh lệch thép sơn vân gỗ, có vách kính',
            'day_canh': '50',
            'quy_cach_canh': '4_canh_lech',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_chinh',
        },
        {
            'id': 690,
            'name': 'A44 Cửa đi 4 cánh cân thép sơn vân gỗ, không ô thoáng',
            'day_canh': '50',
            'quy_cach_canh': '4_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_chinh',
        },
        {
            'id': 691,
            'name': 'A44-Fix Cửa đi 4 cánh cân thép sơn vân gỗ, ô thoáng fix',
            'day_canh': '50',
            'quy_cach_canh': '4_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_chinh',
        },
        {
            'id': 692,
            'name': 'A44-K Cửa đi 4 cánh cân thép sơn vân gỗ, ô thoáng kính',
            'day_canh': '50',
            'quy_cach_canh': '4_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_chinh',
        },
        {
            'id': 693,
            'name': 'A44-NC Cửa đi 4 cánh cân thép sơn vân gỗ, ô thoáng nan chớp',
            'day_canh': '50',
            'quy_cach_canh': '4_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_chinh',
        },
        {
            'id': 697,
            'name': 'A44-SH Cửa đi 4 cánh cân thép sơn vân gỗ, ô thoáng sen hoa',
            'day_canh': '50',
            'quy_cach_canh': '4_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_chinh',
        },
        {
            'id': 696,
            'name': 'A44-V Cửa đi 4 cánh cân thép sơn vân gỗ, ô thoáng vòm',
            'day_canh': '50',
            'quy_cach_canh': '4_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_chinh',
        },
        {
            'id': 695,
            'name': 'A44-VFix Cửa đi 4 cánh cân thép sơn vân gỗ, có vách fix',
            'day_canh': '50',
            'quy_cach_canh': '4_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_chinh',
        },
        {
            'id': 694,
            'name': 'A44-VK Cửa đi 4 cánh cân thép sơn vân gỗ, có vách kính',
            'day_canh': '50',
            'quy_cach_canh': '4_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_chinh',
        },
        {
            'id': 678,
            'name': 'ATL22 Cửa 2 cánh thép sơn vân gỗ kính bản lề thủy lực',
            'day_canh': '50',
            'quy_cach_canh': '2_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_chinh',
        },
        {
            'id': 680,
            'name': 'ATL22-K Cửa 2 cánh thép sơn vân gỗ kính bản lề thủy lực, ô thoáng kính',
            'day_canh': '50',
            'quy_cach_canh': '2_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_chinh',
        },
        {
            'id': 679,
            'name': 'ATL22-V Cửa 2 cánh thép sơn vân gỗ kính bản lề thủy lực, ô thoáng vòm',
            'day_canh': '50',
            'quy_cach_canh': '2_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_chinh',
        },
        {
            'id': 681,
            'name': 'ATL22-VK Cửa 2 cánh kính thép sơn vân gỗ bản lề thủy lực, có vách kính',
            'day_canh': '50',
            'quy_cach_canh': '2_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'cua_chinh',
        },
    ],
    [TYPE.CANH]: [
        {
            'id': 931,
            'name': 'A.CS1 Cánh',
            'day_canh': '40',
            'quy_cach_canh': '1_canh',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 932,
            'name': 'A.CS1-K Cánh',
            'day_canh': '40',
            'quy_cach_canh': '1_canh',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 933,
            'name': 'A.CS1-NC Cánh',
            'day_canh': '40',
            'quy_cach_canh': '1_canh',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 934,
            'name': 'A.CS1-V Cánh',
            'day_canh': '40',
            'quy_cach_canh': '1_canh',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 935,
            'name': 'A.CS2 Cánh',
            'day_canh': '40',
            'quy_cach_canh': '2_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 936,
            'name': 'A.CS2-K Cánh',
            'day_canh': '40',
            'quy_cach_canh': '2_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 937,
            'name': 'A.CS2-NC Cánh',
            'day_canh': '40',
            'quy_cach_canh': '2_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 938,
            'name': 'A.CS2-V Cánh',
            'day_canh': '40',
            'quy_cach_canh': '2_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 939,
            'name': 'A.CS3 Cánh',
            'day_canh': '40',
            'quy_cach_canh': '3_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 940,
            'name': 'A.CS3-K Cánh',
            'day_canh': '40',
            'quy_cach_canh': '3_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 941,
            'name': 'A.CS3-NC Cánh',
            'day_canh': '40',
            'quy_cach_canh': '3_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 942,
            'name': 'A.CS3-V Cánh',
            'day_canh': '40',
            'quy_cach_canh': '3_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 943,
            'name': 'A.CS4 Cánh',
            'day_canh': '40',
            'quy_cach_canh': '4_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 944,
            'name': 'A.CS4-K Cánh',
            'day_canh': '40',
            'quy_cach_canh': '4_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 945,
            'name': 'A.CS4-NC Cánh',
            'day_canh': '40',
            'quy_cach_canh': '4_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 946,
            'name': 'A.CS4-V Cánh',
            'day_canh': '40',
            'quy_cach_canh': '4_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 889,
            'name': 'A1 Cánh',
            'day_canh': '50',
            'quy_cach_canh': '1_canh',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 891,
            'name': 'A1-K Cánh',
            'day_canh': '50',
            'quy_cach_canh': '1_canh',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 892,
            'name': 'A1-NC Cánh',
            'day_canh': '50',
            'quy_cach_canh': '1_canh',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 894,
            'name': 'A1-SH Cánh',
            'day_canh': '50',
            'quy_cach_canh': '1_canh',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 888,
            'name': 'A1-TC Cánh',
            'day_canh': '50',
            'quy_cach_canh': '1_canh',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 893,
            'name': 'A1-V Cánh',
            'day_canh': '50',
            'quy_cach_canh': '1_canh',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 890,
            'name': 'A1-fix Cánh',
            'day_canh': '50',
            'quy_cach_canh': '1_canh',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 903,
            'name': 'A21 Cánh',
            'day_canh': '50',
            'quy_cach_canh': '2_canh_lech',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 905,
            'name': 'A21-K Cánh',
            'day_canh': '50',
            'quy_cach_canh': '2_canh_lech',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 906,
            'name': 'A21-NC Cánh',
            'day_canh': '50',
            'quy_cach_canh': '2_canh_lech',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 910,
            'name': 'A21-SH Cánh',
            'day_canh': '50',
            'quy_cach_canh': '2_canh_lech',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 909,
            'name': 'A21-V Cánh',
            'day_canh': '50',
            'quy_cach_canh': '2_canh_lech',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 907,
            'name': 'A21-VK Cánh',
            'day_canh': '50',
            'quy_cach_canh': '2_canh_lech',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 908,
            'name': 'A21-Vfix Cánh',
            'day_canh': '50',
            'quy_cach_canh': '2_canh_lech',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 904,
            'name': 'A21-fix Cánh',
            'day_canh': '50',
            'quy_cach_canh': '2_canh_lech',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 895,
            'name': 'A22 Cánh',
            'day_canh': '50',
            'quy_cach_canh': '2_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 897,
            'name': 'A22-K Cánh',
            'day_canh': '50',
            'quy_cach_canh': '2_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 898,
            'name': 'A22-NC Cánh',
            'day_canh': '50',
            'quy_cach_canh': '2_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 902,
            'name': 'A22-SH Cánh',
            'day_canh': '50',
            'quy_cach_canh': '2_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 901,
            'name': 'A22-V Cánh',
            'day_canh': '50',
            'quy_cach_canh': '2_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 899,
            'name': 'A22-VK Cánh',
            'day_canh': '50',
            'quy_cach_canh': '2_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 900,
            'name': 'A22-Vfix Cánh',
            'day_canh': '50',
            'quy_cach_canh': '2_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 896,
            'name': 'A22-fix Cánh',
            'day_canh': '50',
            'quy_cach_canh': '2_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 915,
            'name': 'A42 Cánh',
            'day_canh': '50',
            'quy_cach_canh': '4_canh_lech',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 917,
            'name': 'A42-K Cánh',
            'day_canh': '50',
            'quy_cach_canh': '4_canh_lech',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 918,
            'name': 'A42-NC Cánh',
            'day_canh': '50',
            'quy_cach_canh': '4_canh_lech',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 922,
            'name': 'A42-SH Cánh',
            'day_canh': '50',
            'quy_cach_canh': '4_canh_lech',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 921,
            'name': 'A42-V Cánh',
            'day_canh': '50',
            'quy_cach_canh': '4_canh_lech',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 919,
            'name': 'A42-VK Cánh',
            'day_canh': '50',
            'quy_cach_canh': '4_canh_lech',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 920,
            'name': 'A42-Vfix Cánh',
            'day_canh': '50',
            'quy_cach_canh': '4_canh_lech',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 916,
            'name': 'A42-fix Cánh',
            'day_canh': '50',
            'quy_cach_canh': '4_canh_lech',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 923,
            'name': 'A44 Cánh',
            'day_canh': '50',
            'quy_cach_canh': '4_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 925,
            'name': 'A44-K Cánh',
            'day_canh': '50',
            'quy_cach_canh': '4_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 926,
            'name': 'A44-NC Cánh',
            'day_canh': '50',
            'quy_cach_canh': '4_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 930,
            'name': 'A44-SH Cánh',
            'day_canh': '50',
            'quy_cach_canh': '4_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 929,
            'name': 'A44-V Cánh',
            'day_canh': '50',
            'quy_cach_canh': '4_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 927,
            'name': 'A44-VK Cánh',
            'day_canh': '50',
            'quy_cach_canh': '4_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 928,
            'name': 'A44-Vfix Cánh',
            'day_canh': '50',
            'quy_cach_canh': '4_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 924,
            'name': 'A44-fix Cánh',
            'day_canh': '50',
            'quy_cach_canh': '4_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 911,
            'name': 'ATL22 Cánh',
            'day_canh': '50',
            'quy_cach_canh': '2_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 913,
            'name': 'ATL22-K Cánh',
            'day_canh': '50',
            'quy_cach_canh': '2_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 912,
            'name': 'ATL22-V Cánh',
            'day_canh': '50',
            'quy_cach_canh': '2_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 914,
            'name': 'ATL22-VK Cánh',
            'day_canh': '50',
            'quy_cach_canh': '2_canh_can',
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 2463,
            'name': 'Cánh cửa sổ loại 1 cánh',
            'day_canh': '40',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 2465,
            'name': 'Cánh cửa sổ loại 2 cánh',
            'day_canh': '40',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 2461,
            'name': 'Cánh cửa đi loại 1 cánh',
            'day_canh': '50',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
        {
            'id': 2462,
            'name': 'Cánh cửa đi loại 2 cánh',
            'day_canh': '50',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'canh',
        },
    ],
    [TYPE.KHUNG]: [
        {
            'id': 869,
            'name': 'A.CS1 Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 870,
            'name': 'A.CS1-K Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 871,
            'name': 'A.CS1-NC Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 872,
            'name': 'A.CS1-V Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 873,
            'name': 'A.CS2 Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 874,
            'name': 'A.CS2-K Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 875,
            'name': 'A.CS2-NC Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 876,
            'name': 'A.CS2-V Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 877,
            'name': 'A.CS3 Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 878,
            'name': 'A.CS3-K Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 879,
            'name': 'A.CS3-NC Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 880,
            'name': 'A.CS3-V Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 881,
            'name': 'A.CS4 Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 882,
            'name': 'A.CS4-K Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 883,
            'name': 'A.CS4-NC Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 884,
            'name': 'A.CS4-V Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 827,
            'name': 'A1 Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 829,
            'name': 'A1-K Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 830,
            'name': 'A1-NC Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 832,
            'name': 'A1-SH Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 826,
            'name': 'A1-TC Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 831,
            'name': 'A1-V Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 828,
            'name': 'A1-fix Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 841,
            'name': 'A21 Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 843,
            'name': 'A21-K Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 844,
            'name': 'A21-NC Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 848,
            'name': 'A21-SH Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 847,
            'name': 'A21-V Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 845,
            'name': 'A21-VK Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 846,
            'name': 'A21-Vfix Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 842,
            'name': 'A21-fix Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 833,
            'name': 'A22 Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 835,
            'name': 'A22-K Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 836,
            'name': 'A22-NC Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 840,
            'name': 'A22-SH Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 839,
            'name': 'A22-V Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 837,
            'name': 'A22-VK Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 838,
            'name': 'A22-Vfix Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 834,
            'name': 'A22-fix Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 853,
            'name': 'A42 Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 855,
            'name': 'A42-K Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 856,
            'name': 'A42-NC Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 860,
            'name': 'A42-SH Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 859,
            'name': 'A42-V Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 857,
            'name': 'A42-VK Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 858,
            'name': 'A42-Vfix Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 854,
            'name': 'A42-fix Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 861,
            'name': 'A44 Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 863,
            'name': 'A44-K Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 864,
            'name': 'A44-NC Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 868,
            'name': 'A44-SH Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 867,
            'name': 'A44-V Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 865,
            'name': 'A44-VK Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 866,
            'name': 'A44-Vfix Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 862,
            'name': 'A44-fix Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 849,
            'name': 'ATL22 Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 851,
            'name': 'ATL22-K Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 850,
            'name': 'ATL22-V Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
        {
            'id': 852,
            'name': 'ATL22-VK Khung',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'khung',
        },
    ],
    [TYPE.PHAO]: [
        {
            'id': 1543,
            'name': 'Phào rời (Cửa  sổ)',
            'day_canh': '50',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'phao',
        },
        {
            'id': 887,
            'name': 'Phào rời (Cửa chính)',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'phao',
        },
        {
            'id': 885,
            'name': 'Phào đại 200mm',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'phao',
        },
        {
            'id': 886,
            'name': 'Phào đại 250mm',
            'day_canh': '0',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'phao',
        },
    ],
    [TYPE.O_THOANG]: [
        {
            'id': 2969,
            'name': 'Ô thoáng rời fix huỳnh- FIX.SX',
            'day_canh': '50',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'o_thoang',
        },
        {
            'id': 2968,
            'name': 'Ô thoáng rời kính - TK.SX',
            'day_canh': '50',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'o_thoang',
        },
        {
            'id': 2971,
            'name': 'Ô thoáng rời nan chớp - NC.SX',
            'day_canh': '50',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'o_thoang',
        },
        {
            'id': 2970,
            'name': 'Ô thoáng rời sen hoa - SH.SX',
            'day_canh': '50',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'o_thoang',
        },
        {
            'id': 2972,
            'name': 'Ô thoáng rời vòm kính - VK.SX',
            'day_canh': '50',
            'quy_cach_canh': false,
            'ma_huynh_giua': '',
            'ma_huynh_ngoai': '',
            'chung_loai': 'o_thoang',
        },
    ],
};
